language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t shivsharma07/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shivsharma07/react-test npm test -- --coverage

after_success:
  - docker build -t shivsharma07/multi-client ./client
  - docker build -t shivsharma07/multi-nginx ./nginx
  - docker build -t shivsharma07/multi-server ./server
  - docker build -t shivsharma07/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker hub
  - docker push shivsharma07/multi-client
  - docker push shivsharma07/multi-nginx
  - docker push shivsharma07/multi-server
  - docker push shivsharma07/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-928116199751
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
